### PR TITLE
Support all attributes kind in protocols

### LINKED ISSUE #57: bug: Infrahubctl protocols doesn't support all attribute kind
### Component

Python SDK, infrahubctl

### Infrahub SDK version

0.14

### Current Behavior

When I try to generate protocols for my schema it fails if my schema contains node with attributes of certain kind.

### Expected Behavior

I expect my command to pass and generate protocols

### Steps to Reproduce

- invoke demo.stop demo.destroy demo.build demo.start
- load the following schema

```yml
version: "1.0"

nodes:
  - name: FullAttributesNode
    namespace: Example
    description: "Node with all possible attribute kinds"
    attributes:
      - name: identifier
        kind: ID
      - name: text_attribute
        kind: Text
      - name: text_area_attribute
        kind: TextArea
      - name: datetime_attribute
        kind: DateTime
      - name: email_attribute
        kind: Email
      - name: password_attribute
        kind: Password
      - name: hashed_password_attribute
        kind: HashedPassword
      - name: url_attribute
        kind: URL
      - name: file_attribute
        kind: File
      - name: mac_address_attribute
        kind: MacAddress
      - name: color_attribute
        kind: Color
      - name: number_attribute
        kind: Number
      - name: bandwidth_attribute
        kind: Bandwidth
      - name: ip_host_attribute
        kind: IPHost
      - name: ip_network_attribute
        kind: IPNetwork
      - name: boolean_attribute
        kind: Boolean
      - name: checkbox_attribute
        kind: Checkbox
      - name: list_attribute
        kind: List
      - name: json_attribute
        kind: JSON
      - name: any_attribute
        kind: Any
      - name: dropdown_attribute
        kind: Dropdown
        choices:
          - name: option_1
            label: Option 1
            color: "#7fbf7f"
          - name: option_2
            label: Option 2
            color: "#ffff7f"
```

- Then run `infrahubctl protocols`

### Additional Information

So far are not supported: 
- [x] `Bandwidth`
- [x] `Color`
- [x] `Checkbox`
- [x] `ID`
- [x] `Email`
- [x] `MacAddress`
- [x] `File`
- [x] `Any`

Seems to be missing in this map: https://github.com/opsmill/infrahub-sdk-python/blob/develop/infrahub_sdk/code_generator.py#L71

This is the error returned by the command:
```
infrahub-py3.12➜  infrahub git:(develop) ✗ infrahubctl protocols --branch main                
Error: 'email'
Traceback (most recent call last):
  File "/Users/Baptiste/Workspaces/Infrahub/infrahub/python_sdk/infrahub_sdk/ctl/utils.py", line 89, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Baptiste/Workspaces/Infrahub/infrahub/python_sdk/infrahub_sdk/ctl/cli_commands.py", line 356, in protocols
    write_to_file(output_file, code_generator.render(sync=sync))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Baptiste/Workspaces/Infrahub/infrahub/python_sdk/infrahub_sdk/code_generator.py", line 53, in render
    return template.render(
           ^^^^^^^^^^^^^^^^
  File "/Users/Baptiste/Library/Caches/pypoetry/virtualenvs/infrahub-6p6-ZiP_-py3.12/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/Baptiste/Library/Caches/pypoetry/virtualenvs/infrahub-6p6-ZiP_-py3.12/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 73, in top-level template code
  File "/Users/Baptiste/Workspaces/Infrahub/infrahub/python_sdk/infrahub_sdk/code_generator.py", line 90, in _jinja2_filter_render_attribute
    attribute_kind = attribute_kind_map
                     ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'email'
```

### PR DESCRIPTION
**Pull request by BaptisteGi**
relates #57

### CODE REVIEW

**Comment by BaptisteGi** [comment]
@dgarros I added the support for `Checkbox` kind, is it heading the right way? (so I can pretty much do the same thing for the others)

The `infrahubctl protocols` command works fine on a schema containing checkbox with that modification.

**Review by dgarros — APPROVED** [review]
LGTM

**Comment by BaptisteGi** [comment]
Not quite sure about the implementation here:
- I created a class for each possible kind
- Then had to append "Attribute" to the name to avoid collisions
- So it generates protocols with exact same type as user would expect it to be from the schema
- Even tho it's mapped to something else (e.g. str) behind the scene

Example generated:
```python
class ExampleFullAttributesNode(CoreNode):
    id_required: IDAttribute
    id_optional: IDAttributeOptional
    text_required: TextAttribute
    text_optional: TextAttributeOptional
    textarea_required: TextAreaAttribute
    textarea_optional: TextAreaAttributeOptional
    datetime_required: DateTimeAttribute
    datetime_optional: DateTimeAttributeOptional
    email_required: EmailAttribute
    email_optional: EmailAttributeOptional
    password_required: PasswordAttribute
    password_optional: PasswordAttributeOptional
    hashed_password_required: HashedPasswordAttribute
    hashed_password_optional: HashedPasswordAttributeOptional
    url_required: URLAttribute
    url_optional: URLAttributeOptional
    file_required: FileAttribute
    file_optional: FileAttributeOptional
    mac_address_required: MacAddressAttribute
    mac_address_optional: MacAddressAttributeOptional
    color_required: ColorAttribute
    color_optional: ColorAttributeOptional
    number_required: NumberAttribute
    number_optional: NumberAttributeOptional
    bandwidth_required: BandwidthAttribute
    bandwidth_optional: BandwidthAttributeOptional
    ip_host_required: IPHostAttribute
    ip_host_optional: IPHostAttributeOptional
    ip_network_required: IPNetworkAttribute
    ip_network_optional: IPNetworkAttributeOptional
    boolean_required: BooleanAttribute
    boolean_optional: BooleanAttributeOptional
    checkbox_required: CheckboxAttribute
    checkbox_optional: CheckboxAttributeOptional
    list_required: ListAttribute
    list_optional: ListAttributeOptional
    json_required: JSONAttribute
    json_optional: JSONAttributeOptional
    any_required: AnyAttribute
    any_optional: AnyAttributeOptional
    dropdown_required: DropdownAttribute
    dropdown_optional: DropdownAttributeOptional
    profiles: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager
```

**Comment by BaptisteGi** [comment]
- [x] Fix unit tests
- [x] Add changelog

**Comment by petercrocker** [comment]
This came up today with another deployment, so would be great to finish this off and make a new SDK build asap. FYI @wvandeun

**Pull request closed without merging**
